In [1]:
import pandas as pd
import glob

In [9]:

# find all csv files in folder "Stock Data"
csv_files = glob.glob("/Users/jan/Techlabs_Project_Data/Data/*.csv") 
# read all csv files -> all files have the same structure
df_list = [pd.read_csv(file) for file in csv_files] 
#combine all csv files to one dataframe
stock_data = pd.concat(df_list, ignore_index=True)

In [15]:
 #Adjust Date Format and add percentage of difference between open and close price
stock_data['Date']=pd.to_datetime(stock_data['Date'], format= 'ISO8601', utc=True)
stock_data['percentage_difference_open_close'] = ((stock_data['Close']-stock_data['Open'])/stock_data['Open'])*100

In [27]:
#read data natural disaster
earthquakes_data = pd.read_csv('/Users/jan/Techlabs_Project_Data/Eartquakes-1990-2023.csv')

In [45]:
#Adjust Date Format and drop columns time, status and tsunami. Filter data for years 2008 and later, magnitute over 6
earthquakes_data['date']=pd.to_datetime(earthquakes_data['date'], format= 'ISO8601')
earthquakes_data = earthquakes_data[(earthquakes_data['date'].dt.year>=2008)]
earthquake_data = earthquakes_data.loc[earthquakes_data['magnitudo']>=6]

In [46]:
# prepare date columns to act as primary key & Make sure that both columns are in the same datetime format
stock_data.rename(columns={'Date':'date'},inplace=True) #rename date columns in stock_data

earthquakes_data["date"] = pd.to_datetime(earthquakes_data["date"]).dt.date 
stock_data["date"] = pd.to_datetime(stock_data["date"]).dt.date

In [48]:
#merge stock_data and earthquake_data to one dataframe.primary key is the date
disaster_stock_data = earthquakes_data.merge(stock_data, on = 'date', how= 'outer')
disaster_stock_data = disaster_stock_data.sort_values(by=["date"])

In [ ]:
# Convert date to datetime & add new column year to filter data by year
disaster_stock_data['year'] = pd.to_datetime(disaster_stock_data['date']).dt.year

In [ ]:
#check if all columns are in the dataframe
disaster_stock_data.head()

,place,significance,data_type,magnitudo,state,longitude,latitude,depth,date,Ticker,Open,High,Low,Close,Adj Close,Volume,percentage_difference_open_close,year
0,"14 km ENE of Fox, Alaska",22.0,explosion,1.20,Alaska,-147.333600,64.999400,0.000,2008-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008
174,"4 km SW of Cobb, California",14.0,earthquake,0.97,California,-122.761667,38.792000,1.032,2008-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008
175,"12 km SE of Clear, Alaska, Alaska",12.0,earthquake,0.90,Alaska,-149.014600,64.173700,1.000,2008-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008
176,"2 km SSE of Mesa, California",4.0,earthquake,0.48,California,-118.534333,37.398333,10.846,2008-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008
177,"56 km SE of Punta Cana, Dominican Republic",178.0,earthquake,3.40,Dominican Republic,-68.034000,18.210000,107.200,2008-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008